### ISSUE TITLE
Problem updating to 10.14.4

### ISSUE THREAD

**Issue by alexmenn** [bavariancake/XPS9570-macOS#10]
Hello @bavariancake !!

I have some troubles updating to 10.14.4.

Im following your instructions, but when I try to boot to install partition after first reboot, after 15-20 mins, my xps reboots. Let me explain all the steps I do:

1) I boot in my 10.14.2 system with my actual EFI folder (I upload it, its EFI1.zip). 
2) I enter in system preferences and click in "download and install 10.14.4".
3) I reboot my system and progress bar appears 1-2 minutes and then reboot.
4) I boot to install partition with EFI2 (different EFI installed in my usb). This is the EFI folder configured with the new hd630 framebuffer patches you said in your guide. Here is where I have the problems. After waiting 15 or 20 minutes, my system reboots, and I cant boot successfuly. I upload too EFI2.zip.

I've tried to boot with xitgun EFI folder and it boots, but I really dont like it, because he uses lot of kexts and configs without optimization, and when I boot to 10.14.4 its sooooo slow with his EFI, so, discarted.

Im trying to boot only with kext in Clover/Kext/other , I uninstalled 10.14.2 kexts from /Library/Extensions and rebuilded cache, but without success. 

What is wrong?

EFI1: https://drive.google.com/file/d/1VzJp3LPYt1_DGCe9S2LpM3egDxC-RvYe/view?usp=sharing

EFI2: https://drive.google.com/file/d/1ad7jgPT0U9nA3lDnkB-pIP0xjm_KMaEi/view?usp=sharing

**Comment by alexmenn** [comment]
SOLVED!! I could update finally.

**Comment by bavariancake** [comment]
Could you explain what the issue was and how you solved it? This will help others who run into the same problem.

**Comment by bavariancake** [comment]
@alexmenn ping.
