### ISSUE TITLE
DW1830 Bluetooth unavailable from sleep in battery

### ISSUE THREAD

**Issue by LuletterSoul** [bavariancake/XPS9570-macOS#11]
Hello everyone, I am looking for a solution for DW1830 BT unavailable from sleep in battery.
ISSUE description:
* DW1830 BT is detected as BCM2045A0 when come out from sleep while in battery --> BT doesn't work properly: BT status turns into unavailable after a while.
* DW1830 BT is detected as BCM920703 when come out from sleep while on AC --> BT works with zero issue

[See more discussions about this issue](https://www.tonymacx86.com/threads/dw1830-bluetooth-not-available-power-saving-issue.246350/page-5)

**Comment by bavariancake** [comment]
It looks like the BT device is actually a BCM20703, but I do see BCM2045A0 listed in the boot longs. Perhaps the firmware uploaded to the device during boot identifies itself as BCM2045A0.

Have you tried these boot flags in the [OS-X-BrcmPatchRAM](https://github.com/RehabMan/OS-X-BrcmPatchRAM) readme? Does it change the outcome?

`bpr_probedelay=100 bpr_initialdelay=300 bpr_postresetdelay=300`
or:
`bpr_probedelay=200 bpr_initialdelay=400 bpr_postresetdelay=400`

What does your sys log show for BrcmPatchRAM logs when sleeping/resuming?

`log show --predicate 'process == "kernel"' --style syslog --source --debug --last 120m | grep BrcmPatchRAM`

**Comment by LuletterSoul** [comment]
@bavariancake Thanks for your kind help!I am sorry for so late to response.I am busy at university now.
I read the README of BrcmPatchRAM before , I tested two options and no effect.

Here is the what my sys log show:
<img width="1442" alt="Screen Shot 2019-05-11 at 12 11 13 PM" src="https://user-images.githubusercontent.com/21377419/57565066-32e5b580-73e9-11e9-8606-610ee9e2070d.png">

It seems that the firmware has only been loaded once.Then BT became unavailable. 
BCM2045A0 is actually a wrong  device name.

**Comment by bavariancake** [comment]
I was able to reproduce this issue a couple of times. Still looking into it...

**Comment by wormz30** [comment]
any updates on this?

**Comment by LuletterSoul** [comment]
@wormz30 I found a hardware solution.It could be fixed by disabling `Pin 56` and `Pin 54` successfully.Check  [jaymonkey’s post](https://www.tonymacx86.com/threads/bluetooth-randomly-not-available-after-sleep.266255/#post-1862126) to see more details.
