### ISSUE TITLE
The audio board is not driven, I don't know why.

### ISSUE THREAD

**Issue by w962402254** [bavariancake/XPS9570-macOS#13]
The audio board  is not driven, I don't know why.
![image](https://user-images.githubusercontent.com/27877696/56815648-78947100-6874-11e9-9ef7-67fbe978f3cf.png)  

Boot the clover interface that audio option prompt 'unknow HDA device vendor 8086, model a348'
Can you help me answer it, thank you very much.

**Comment by bavariancake** [comment]
Can you boot into macOS, or are you stuck during boot?

If you can boot into macOS, is there no audio interface? Or do you hear no sound?

Check if you have the latest version of AppleALC, and rebuild your caches (`sudo kextcache -i /`), and reboot. Check that you have a recent version of Clover, preferably the RehabMan build. Both versions from this repo should work.

**Comment by w962402254** [comment]
At first, thank you for your reply.
Later I tried to refresh the cache and reinstall the driver. There is a sound after booting. I suspect that there is a problem with the driver conflict.



------------------ 原始邮件 ------------------
发件人: "Bavarian Cake"<notifications@github.com>;
发送时间: 2019年4月30日(星期二) 下午2:03
收件人: "bavariancake/XPS9570-macOS"<XPS9570-macOS@noreply.github.com>;
抄送: "王小白"<962402254@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [bavariancake/XPS9570-macOS] The audio board is not driven, Idon't know why. (#13)




Can you boot into macOS, or are you stuck during boot?
 
If you can boot into macOS, is there no audio interface? Or do you hear no sound?
 
Check if you have the latest version of AppleALC, and rebuild your caches (sudo kextcache -i /), and reboot. Check that you have a recent version of Clover, preferably the RehabMan build. Both versions from this repo should work.

**Comment by bavariancake** [comment]
I've noticed that sometimes you have to run `sudo kextcache -i /` two times (and reboot two times). Not sure why. Glad it's working, marking issue closed.
