### ISSUE TITLE
Testing needed for 1080p version

### ISSUE THREAD

**Issue by urielbeaupre** [bavariancake/XPS9570-macOS#14]
Hey I have the 1080p version of this model, anyone has experience with that?

**Comment by attilagyorffy** [comment]
I have the same model, an XPS 9570 from 2018 and would love to know as well please. I have *some* of the features working but not all. (for example sleep OR some bugs on audio)

**Comment by M69W** [comment]
Maybe you can see here [CLOVER/config.plist#L517](https://github.com/M69W/XPS-15-9570-macOS-Mojave/blob/master/CLOVER/config.plist#L517)，1080P needs two patches and need to remove 4k patche. Because they don't seem to work together.
And I found 1080P and 4K laptop that is only difference is the screen for hackintosh.

**Comment by bavariancake** [comment]
As far as I know, the only difference would be the monitor, and the only change you _should_ need to make is the one @M69W is referring to. Try it out and report back @urielbeaupre and @attilagyorffy. If other changes are needed (probably not), we can update the repo to support both. If no other changes are needed, we can mention that in the readme as well.

**Comment by M69W** [comment]
Sorry to your  Pull requests that I 'm not familier with Git.I refork your respository.

https://github.com/M69W/XPS9570-macOS/commit/e977b8ab0b59420f88f602efbae78aa1027a67d5
Need CLOVERX64.efi( [latest version](https://github.com/Dids/clover-builder/releases) ) and two patches for 1080P version.
your CLOVERX64.efi seems to not work in my laptop.

PS: My Laptop is XPS 9570 i5-8300h DW1560

**Comment by bavariancake** [comment]
@M69W this is good progress.

You should not use both the WhateverGreen `dpcd-max-link-rate` setting and the kext patches "ALT: Set max link rate to 0x0A (HBR)" at the same time. They do the same thing.

Can you remove the kext patches and test with only `dpcd-max-link-rate`? Does it work?

**Comment by M69W** [comment]
remove the kext patches and test with only dpcd-max-link-rate
your CLOVERX64.efi is not work. Maybe it's too old to suppert some attributes.
Use CLOVERX64.efi( [latest version](https://github.com/Dids/clover-builder/releases) ) is work now.

**Comment by bavariancake** [comment]
> Use CLOVERX64.efi( [latest version](https://github.com/Dids/clover-builder/releases) ) is work now.
> The latest CLOVERX64.efi would soved [this issue](https://github.com/bavariancake/XPS9570-macOS#2019-05-17-upgrade-to-10145)
> `busy timeout[0], (240s) kextd wait(0): 'AppleACPICPU'`

Thanks for testing this. I updated Clover to the latest build and put everything into one `EFI` folder. You should be able to install or use this folder for normal booting. Hopefully much easier now.

**Comment by derekxu16** [comment]
I just got OSX to dual boot successfully on my 9570 with 1080p display. It worked perfectly, all I did was use Clover Configurator to change the `dpcd-max-link-rate` setting in config,plist. I didn't alter any of the other kexts or patches. Thank you!

**Comment by bavariancake** [comment]
Since the 1080p version works with the expected link rate setting, I'm going to close this issue.
