### ISSUE TITLE
Touchpad Enhancement

### ISSUE THREAD

**Issue by NoctiZen** [bavariancake/XPS9570-macOS#17]
The [new VoodooPS2 driver](https://github.com/acidanthera/VoodooPS2) bases itself upon Rehabman's version and offers more native gesture expericence by emulating Magic Trackpad. I guess you may want to have a try.

**Comment by bavariancake** [comment]
Thanks for the tip! It does seem a bit better than the old driver.

I couldn't get dragging to work. Do I have to configure something?

**Comment by NoctiZen** [comment]
> Thanks for the tip! It does seem a bit better than the old driver.
> 
> I couldn't get dragging to work. Do I have to configure something?
You can configure the drag options in the Accessibility setting or directly disable the Force Touch emulation :)

**Comment by NoctiZen** [comment]
> Thanks for the tip! It does seem a bit better than the old driver.
> 
> I couldn't get dragging to work. Do I have to configure something?

You can configure the drag options in the Accessibility setting or directly disable the Force Touch emulation :)

**Comment by bavariancake** [comment]
I realized that I normally click with one finger and drag with another, but that doesn't work with this driver. If I click down and drag with the same finger, it works.

After playing with this for a while, it seems like it loses input events occasionally. Especially noticeable when changing scroll direction with two-finger scroll. The VooodooI2C driver feels much more usable, but is too unstable.

**Comment by trevorstarick** [comment]
VoodooI2C recently got support for the 8th-gen CPUs which makes it noticeably smoother. You'll need to patch your DSDT

**Comment by d3myz** [comment]
Any chance you could advise on how to patch the DSDT for the VoodooI2c kext?

**Comment by bavariancake** [comment]
Closing this issue now that the VoodooI2C driver has been added to the repo. Not that it's 100% perfect, but it is much better than before.
