### ISSUE TITLE
lid close kernel panic

### ISSUE THREAD

**Issue by weissi29** [bavariancake/XPS9570-macOS#19]
first of all - thanks! great work!!

i just have 1 issue now. i've connected 2 displayport monitors via dockingstation which is working perfectly. but when i close the lid (to turn off laptop monitor) it crashes with kernel panic. i've attached the panic.
i disabled sleep in terminal like described in the readme. any idea?
[Kernel_2019-05-21-082327_MacBook-Pro.txt](https://github.com/bavariancake/XPS9570-macOS/files/3201116/Kernel_2019-05-21-082327_MacBook-Pro.txt)

**Comment by bavariancake** [comment]
Interesting. We'll probably have to try different WEG connector/port setups.

Does the KP only happen when you close the lid, but not in sleep mode with lid open?

What happens with only 1 DP monitor? With no DP connections? If you close the lid during BIOS post with 2 DP attached?

Do you have anything attached to the HDMI port?

**Comment by weissi29** [comment]
the panic is gone, so I will close this
