### ISSUE TITLE
Max brightness is still too low.

### ISSUE THREAD

**Issue by wtdcode** [bavariancake/XPS9570-macOS#3]
I have installed the Hackintosh and make graphics acceleration work, but I find two problems.

- The brightness will become brighter only 3 minutes after booting just as discussed on [tmx](https://www.tonymacx86.com/threads/solved-uhd-630-either-not-booting-or-no-acceleration-on-dell-xps-15-9570-4k.261101/).
- But even after that, the max brightness seems too low, about 30% or lower of that in Windows, which makes it difficult to use.

Do you have the same problem? How do you solve it? I have tried your SSDT-PNLFCFL.aml, but it seems it doesn't work.

**Comment by kevinshroff** [comment]
How did you solve this? Or was this something that Bavariancake fixed

**Comment by wtdcode** [comment]
@kevinshroff I just implemented SSDT-PNLF and SSDT-PNLFCFL by myself. It seems that those of  Bavariancake don't work on my machine.

**Comment by bavariancake** [comment]
@wtdcode - can you share those files here so we can see if there's a fix that will work for everyone? do you have a 4k or 1080 display?

@kevinshroff - are you still having an issue with max brightness? do you have a 4k or 1080 display?

For me, max brightness actually brighter than the Windows max. I actually suspect this may be driving the display a little over its normal 100% setting.
