### ISSUE TITLE
Third WiFi antenna

### ISSUE THREAD

**Issue by romton843** [bavariancake/XPS9570-macOS#30]
Hi, first of all, thank you for your awesome work.
Just wanted to let you know that I did some research and I figured out that the WiFi antenna connector might not be U.FL but Ipex MHF4.
Indeed, U.FL are 2mm (and white) while MHF4 are 1.5mm (and black). Not a big deal but it was a little confusing to me. Thanks again.

**Comment by bavariancake** [comment]
Good catch, I didn't know about MHF4 connectors. I'll update the readme when I get a chance!

**Comment by bavariancake** [comment]
Updated documentation in commit bc4feac3a1087e4390d42b40ec38e0ac01951897 😊
