### ISSUE TITLE
High kernal_task issue caused by touchscreen

### ISSUE THREAD

**Issue by kampofo** [bavariancake/XPS9570-macOS#39]
Looking at fixes for the post installation process from LuLetterSoul I found that the high kernel_task cpu usage is caused by the touch screen. After deleting the VoodooI2C kext which disables the touchscreen I can confirm that does in fact resolve the issue. However I am new to hackintosh-ing and deleting the VoodooI2C kext also disables the trackpad gestures which are incredibly useful for productivity. Is it possible you could release an additional VoodooI2C, that has the touchscreen disabled but the gestures enabled? It does help a bit with battery life.

**Comment by w962402254** [comment]
You can update VoodooI2C-2.6.5.So far, this problem can be solved on my XPS9570.Good luck!
