### ISSUE TITLE
Alternatives to DW1830

### ISSUE THREAD

**Issue by erenatas** [bavariancake/XPS9570-macOS#41]
Hi everyone,

My DW1830 died and the prices of this wifi card is just unbelievable. They are selling maybe a $10 card for ~$80! Do you have any other recommendations? I have checked DW1530 and that card is ridiculously expensive as well. I would be really glad if you could help! Thanks!

Eren

**Comment by M69W** [comment]
Maybe you need DW1820A, it's work on my XPS 9570.
https://blog.daliansky.net/DW1820A_BCM94350ZAE-driver-inserts-the-correct-posture.html

**Comment by mathewjpotter** [comment]
I have the dw1830, its working well. I let you know if it stops

**Comment by erenatas** [comment]
@M69W I will give it a shot with DW1820A which is much cheaper. Thanks a lot!
