### ISSUE TITLE
Hibernate not working

### ISSUE THREAD

**Issue by dhruvdangi** [bavariancake/XPS9570-macOS#44]
I am trying to hibernate my Hackintosh so that I can boot to windows and back easily.
I tried the following command: 
`sudo pmset -b hibernatemode 25` (-b is just for battery, I had my charger plugged out while testing this)
After that, if I click on sleep, it does shut down but when I try to turn it on, it fails the first time and restarts again, then it boots without using the sleepImage.
I can see a 1GB sleepImage is created in `/private/var/vm/sleepimage`
Is there a way to fix this?

**Comment by bavariancake** [comment]
Hibernation is not supported, as described in the readme. If you find a way to make it work, please create a PR.

Since this behavior is expected/documented, I'm going to close this issue, but feel free to comment if you have other issues or a solution for hibernation.
