### ISSUE TITLE
No Sleep

### ISSUE THREAD

**Issue by KSYMEK** [bavariancake/XPS9570-macOS#48]
I don't know is it supported but my XPS 15 do not sleep, hibernate. I tried it by closing lid and by sleep button.

**Comment by calbear92** [comment]
As far as I have seen, Hibernation is not supported. Sleep partially works for me. When I close the lid, the computer does sleep, as well as manually selecting sleep.

However, it wakes up soon thereafter without touching anything. If you leave the computer alone, it will eventually sleep. [My computer is in clamshell mode in a dock and connected via bluetooth keyboard and trackpad on Mojave with Clover 5097, bavariancake's EFI with updated kexts in C/K/O folder- except AppleALC 1.4.0 and L/E with BRCMFirmwareRepo 2.3.0d3].

Upon hitting the keyboard- most of the times it will bring you into the login desktop. However, I have seen color screening anomalies (incorrect color sequences) and at random times, more instances of the spinning beach ball. Seems that the longer the computer was in asleep- the more prevalent this issue might be.

I would then restart and everything is back to normal.

No reproducible sequences as far as I can tell.
