### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by songssam** [bavariancake/XPS9570-macOS#67]
I installed Mojave on USB and swapped Overwrote folder.

While I was installing I got this error message.

It was working fine without a problem with earlier commit

i7-8750H
32 GB ram
2TB 970 Evo
FHD
DW1820A

![error](https://user-images.githubusercontent.com/16694142/74383047-15001380-4db4-11ea-82f4-edaf67a217b1.jpg)

**Comment by duongle26** [comment]
Just want to let you know that recently I did a fresh install of Catalina with lastest commits, and everything is working fine.

**Comment by bavariancake** [comment]
> Just want to let you know that recently I did a fresh install of Catalina with lastest commits, and everything is working fine.

Glad it's working for you, going to close the issue as resolved. Re-open the issue if run into other problems 🙂
