### ISSUE TITLE
USB-C hub ethernet adaptor performance issue

### ISSUE THREAD

**Issue by alexmenn** [bavariancake/XPS9570-macOS#8]
Hi @bavariancake !

Ive bought this USB-C hub https://www.amazon.es/gp/product/B07BBNSYCV/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1

HDMI works great, USB3.0 and card reader too. But ethernet port only gives me 40% of internet speed. I've tried this hub in my original macbook pro, and I get 100% of speed (100mbs) instead of 40mbs. 

Could be related with HS and SS port? I mean, USB-C works as HS and not SS, maybe it fails because of that or because of the USB power issue.

**Comment by bavariancake** [comment]
High-speed USB still gives you 480Mbps, so you shouldn't be limited to to 40Mbps.

Go to network prefs, check that the ethernet adapter is at the top (i.e. preferred), or disable your Wi-Fi for the test to ensure you're not actually going through the wrong adapter. Select your ethernet adapter, go to Advanced -> Hardware, and check that your link speed is negotiated to 1000Mbps. An old or low quality ethernet cable can limit you to 100Mbps or even 10Mbps link speed in extreme cases.

If the issue persists, go to system information -> USB -> select your ethernet adapter built into the multi-hub. You'll see two lines (with different values):

```
Current Available (mA):	900
Current Required (mA):	256
```

If the required current is below the available current, it's not a USB power issue (I'd think it's unlikely anyway).

It's encouraging that the USB C port works for video output - I haven't gotten the internal HDMI port to work yet without instant reboot on hot plug. This is an excellent alternative.

**Comment by alexmenn** [comment]
Ok, I've tested this ethernet cable with a ugreen usb to ethernet adapter (1000mb) and it works perfect, 100mbs speed.

Ive checked too the system info and USB power seems to be OK in usb-c hub ethernet. In hardware - advanced, the speed is 1000mb too, I dont know what happens... Its so strange :( But still low speed.

**Comment by bavariancake** [comment]
It's possible that there is congestion with other devices you have plugged into this hub over a USB 2.0 connection. Check sys info -> usb and see if the ethernet adaptor is connected via HS or SS. Compare this to Mac hardware. Report back if this is the issue. Thanks.

**Comment by alexmenn** [comment]
I dont have other devices connected to hub, just the ethernet cable.
It seems to work with SS USB, but not max speed. Ive tried this hub in xiaomi probook running hackintosh too and it works perfect, btw.
<img width="1008" alt="captura de pantalla 2019-03-06 a las 10 01 37" src="https://user-images.githubusercontent.com/42182041/53868762-07b0a580-3ff7-11e9-9d70-422b394fbecb.png">

**Comment by bavariancake** [comment]
If the adapter negotiates a link at 1000Mbps, is connected with SS USB, has enough power (288mA < 900mA), it becomes difficult to find any fault with the XPS 9570 or that particular hackintosh setup.

You _could_ try using iperf3 to test speeds on your own LAN using that USB adapter, but I would re-test any prior assumptions, e.g. is the network the same, is the ethernet link really 1Gbps, are there CRC errors on that ethernet interface suggesting a bad cable, does another USB -> ethernet adaptor plugged into that same hub have low link speed, etc.

If you're getting full link speed with the Ugreen adapter, sometimes it's better to chalk it up to bad hardware and move on.

Frankly, 4/5 USB combo hubs have some kind of problem - either the signal drops out once per hour (bad signal/noise ratio), the hub overheats, doesn't provide SS, doesn't recognize a device unless you unplug it and plug it back in (I have one of those), has sleep/suspend problems, etc.

Closing issue for now unless you find an issue specific to the XPS 9570 + hackintosh setup, in which case, feel free to leave a comment.
