### ISSUE TITLE
[FIX] Coffee Lake Intel UHD Graphics 630 on macOS Mojave: HDMI Output Issue [Public Testing Stage]

### ISSUE THREAD

**Issue by M69W** [bavariancake/XPS9570-macOS#9]
[[FIX] Coffee Lake Intel UHD Graphics 630 on macOS Mojave: HDMI Output Issue [Public Testing Stage]](https://www.tonymacx86.com/threads/fix-coffee-lake-intel-uhd-graphics-630-on-macos-mojave-hdmi-output-issue-public-testing-stage.275126/)

**Comment by LuletterSoul** [comment]
Report: HDMI output issue has been fixed in my machine.See my repository for more update details
[Dell-XPS-15-9570-macOS-Mojave](https://github.com/LuletterSoul/Dell-XPS-15-9570-macOS-Mojave)

**Comment by M69W** [comment]
> Report: HDMI output issue has been fixed in my machine.See my repository for more update details
> [Dell-XPS-15-9570-macOS-Mojave](https://github.com/LuletterSoul/Dell-XPS-15-9570-macOS-Mojave)

如果方便的话，QQ群：929644389，方便有什么问题一起测试！

**Comment by LuletterSoul** [comment]
> > Report: HDMI output issue has been fixed in my machine.See my repository for more update details
> > [Dell-XPS-15-9570-macOS-Mojave](https://github.com/LuletterSoul/Dell-XPS-15-9570-macOS-Mojave)
> 
> 如果方便的话，QQ群：929644389，方便有什么问题一起测试！

Thanks for your invitaion, but I am used to communicating with you in Github, welcome to post issues in my rep ...

**Comment by M69W** [comment]
OK！
Anyway，Thanks to your job!

**Comment by M69W** [comment]
Public Testing Stage，make it open.

**Comment by 0xFireWolf** [comment]
Stage 2 is now available. The new fix now supports HDMI 2.0 hotplug after the system boots.

Please carefully read the [original thread](https://www.tonymacx86.com/threads/fix-coffee-lake-intel-uhd-graphics-630-on-macos-mojave-hdmi-output-issue-public-testing-stage.275126/) and post your test results **under the original thread**.

**Comment by d3myz** [comment]
I've noticed that when I plug my TV in via HDMI port I am only able to Mirror and extend, but hot plugging does not work at all for me. I also tested this via usb-c Mirror works, but not extend neither does hotplugging.

**Comment by 0xFireWolf** [comment]
Public testing stage finished. WhateverGreen 1.3.0 now contains this fix. Please carefully read the [manual](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md) before you get started.

**Comment by bavariancake** [comment]
Closing this issue since it's been resolved. Thanks again @0xFireWolf!
